### ISSUE TITLE
GraphQL and Typescript filter discrepancy

### ISSUE THREAD

**Issue by hendrik-advantitge** [vendurehq/vendure#1834]
**Describe the bug**
The filter types generated by `createFilterParameter` in `generate-list-options.ts` and the filter types generated by `FilterParameter<T extends VendureEntity>` in `common-types.ts` are not the same. In the resolvers however, they are passed through to the services as if they are the same.

**To Reproduce**
Compare `PromotionFilterParameter` with `FilterParameter<Promotion>`. The last one does not include a filter for `startsAt`, while `PromotionFilterParameter` does include a filter for `startsAt`. The filter with `startsAt` is passed to the service and the filter for the field is applied, although the typing strictly does not allow it.

**Expected behavior**
The GraphQL filters and Typescript filters should have the same typings.

**Environment (please complete the following information):**
 - @vendure/core version: 1.7.3

**Comment by michaelbromley** [comment]
The reason that `FilterParameter<Promotion>` does not pick up on `startsAt` or `endsAt` is because they are nullable types. So I can change the definition of `FilterParameter<T>` to also pick up nullable variants of each data type.

This still leaves an issue with e.g. `FilterParameter<T>` picking up the `priorityScore` field, which is not actually exposed publicly in the GraphQL type and thus is not part of `PromotionFilterParameter`.

For this there is no easy type-level fix, because the type system has no knowledge of which fields on the entity are also exposed via the corresponding GraphQL type. However, this is probably not really an issue, since the ListQueryBuilder will happily work with the `priorityScore` field even if it is not publicly exposed. So as long as the `FilterParameter<T>` is a superset of the corresponding generated type, it should be ok.
