### ISSUE TITLE
Newly created seller cannot log in to the admin dashboard

### ISSUE THREAD

**Issue by chrislaai** [vendurehq/vendure#2207]
**Describe the bug**

**To Reproduce**
1. npx @vendure/create@next my-shop

Create by using [admin-api](http://localhost:3000/admin-api):
```
mutation RegisterSeller {
  registerNewSeller(input: {
    shopName: "Bob's Parts",
     administrator: {
       firstName: "Bob"
       lastName: "Dobalina"
       emailAddress: "bob@bobs-parts.com"
       password: "test",
       roleIds: []
     }
   }) {
     id
     code
     token
   }
}
```

![203216@2x](https://github.com/vendure-ecommerce/vendure/assets/134155599/6fcef13d-90cf-4a21-ba83-f00f47c1e06d)

**Expected behavior**

**Environment (please complete the following information):**
 - @vendure/core version: 2.0.0-beta.3
 - Nodejs version: npm v9.5.1 nodejs v18.16.0
 - Database (mysql/postgres etc): postgres

**Additional context**

**Comment by mpacary** [comment]
Reproduced here:

After migrating for **2.0.0-next.28** to **2.0.0-beta.3**, I can't authenticate as a seller anymore on the admin UI (superadmin is Ok).

More precisely, the authentication succeeds but **any subsequent calls to retrieve products, orders etc. end up with authorization errors & the seller is redirected to the login page**.

I guess that this might be due to a missing `vendure-token` header.

When using the GraphQL playground against `/admin-api`, running a login mutation then an usual operation such as querying orders between two dates, providing only the `Authorization` header still gives permission errors in return.

As soon as I add the "`vendure-token`" header with the seller's channel token, queries work as expected.
